name: fastapi-supabase-jwt
region: sgp1
services:
  - name: web
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_size_slug: basic-xxs
    instance_count: 1
    health_check:
      http_path: /health
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        value: ${JWT_SECRET}
      - key: JWT_EXPIRE_MINUTES
        scope: RUN_TIME
        value: ${JWT_EXPIRE_MINUTES}
routes:
  - path: /
    service_name: web
