name: CI & Deploy (DigitalOcean App Platform)
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (ruff)
        run: ruff .
      - name: Run tests (pytest)
        run: pytest -q

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build-test-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Validate spec
        run: doctl apps spec validate .do/app.yaml
      - name: Create or Update App
        env:
          DO_APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRE_MINUTES: ${{ secrets.JWT_EXPIRE_MINUTES }}
        run: |
          set -euo pipefail
          if [ -z "${DO_APP_ID:-}" ]; then
            echo "No DO_APP_ID provided, creating app..."
            doctl apps create --spec .do/app.yaml > create_out.json
            cat create_out.json
          else
            echo "Updating existing app: $DO_APP_ID"
            doctl apps update "$DO_APP_ID" --spec .do/app.yaml
          fi
